### PR TITLE
Add nodejs installation and fedora installer

### PR DESCRIPTION
**Pull request by prashantbarca**
Add fedora support and nodejs intallation

### CODE REVIEW

**Comment by abishekk92** [comment]
Okay first things first.
- Can you rebase and squash into two commits?
  1. Adding nodejs to the dependencies
  2. Adding a fedora installer.

**Having individual commits makes logical sense. For example if we want to revert one particular checkpoint say addition of node.js, we would be able to do that if they're atomic.**
- Don't build anything in an installation when a binary is readily available. It takes time and is an overkill during automated installation, also makes sure you install the latest stable.
- Use something like this to detect the host distro

``` bash
if [ -f /etc/debian_version ] ; then
    DIST="DEBIAN"
elif [ -f /etc/redhat-release ] ; then
    DIST="REDHAT"
fi

case $DIST in
   'DEBIAN')
   #installation for deb
   ;;

   'REDHAT')
   #installation for red-hat based distros
   ;;
esac
```

**Comment by abishekk92** [comment]
On further inspection you can't rebase and squash a single commit into two. You will have to split that one commit into two. You can get pointers on how to do that from [this](http://stackoverflow.com/questions/1440050/how-to-split-last-commit-into-two-in-git). I would advocate the second approach, however, I would still ask you to understand what is happening and then do it, lest you screw you up your indexes.

**Comment by prashantbarca** [comment]
Thanks for the review, will do the needful asap! :)

**Comment by abishekk92** [comment]
@prashantbarca Sure, take your time. I appreciate your effort.

**Comment by prashantbarca** [comment]
@abishekk92 There is no official deb for debian. There is an rpm though, using that. :)

**Comment by abishekk92** [comment]
You can use use the deb nodejs, which is pretty standard. Or I can also suggest using nvm, but that would become yet another piece of dependency to maintain. You can go ahead and get the unofficial debian.

**Pull request merged**
